import './globals.css'
import { Session } from 'next-auth';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import AuthContext from './AuthContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/session`, {
    headers: {
      cookie,
    },
  });

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //const session = await getSession(headers().get('cookie') ?? '');
  return (
    <html lang="en">
      {/* <AuthContext session={session}>
        <body className={inter.className}>{children}</body>
      </AuthContext> */}
      <body className={inter.className + " w-screen h-screen"}>{children}</body>
    </html>
  )
}
